version: "3.8"
services:

    # PHP service
    app:
        build: .
        container_name: php-app
        working_dir: /var/www/
        volumes:
            - ./app:/var/www
        networks:
            - app-network

    # MySQL database service
    db:
        image: mysql:5.7
        container_name: mysql-db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        env_file:
            - ./.env
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - app-network

    # Nginx service
    nginx:
        image: nginx:alpine
        container_name: php-nginx
        ports:
            - 8000:80
        volumes:
            - ./app:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network
volumes:
    db-data:

networks:
    app-network:
        driver: bridge
